### ISSUE TITLE
quero executar a aplicação

### ISSUE THREAD

**Issue by baldoqui** [JVictorDias/CanhaoDeNewton#1]
Não tenho muito conhecimento em cpp por isso não consegui fazer uma build mas queria muito testar em meu pc, poderia disponibilizar um executável?

**Comment by bpmsilva** [comment]
Eu estou fazendo uma versão do código em JavaScript. Você pode encontrar no meu fork, no branch js-dev: https://github.com/bpmsilva/CanhaoDeNewton/tree/dev-js . No caso, quando eu tento rodar o código diretamente através do navegador, há um erro por configurações de segurança, por isso eu adicionei uma versão de único arquivo, que é o [index_full.html](https://github.com/bpmsilva/CanhaoDeNewton/blob/dev-js/javascript/index_full.html). Deve funcionar perfeitamente se você abrir diretamente através do seu navegador. A versão está bem pobre ainda em termos visuais, mas eu quero investigar algumas melhorias como, por exemplo, conservação da energia mecânica. Se possível, me diz se deu certo depois :)
